#!/bin/bash
#
# Geo-Fail2Ban Installation Script
# Telegram alerts, GeoIP enrichment, AbuseIPDB permanent bans, country geoblock.
#
# Usage:  sudo bash install.sh [--skip-geo]
#   --skip-geo   don't download country zone files / enable the geoblock ipset
#

set -e
cd "$(dirname "$0")"

SKIP_GEO=0
[ "${1:-}" = "--skip-geo" ] && SKIP_GEO=1

# Seconds to wait on each interactive prompt before auto-skipping. Override with
# PROMPT_TIMEOUT=N sudo -E bash install.sh
PROMPT_TIMEOUT="${PROMPT_TIMEOUT:-60}"

# Where all program files are installed. Override with: INSTALL_DIR=/path sudo -E bash install.sh
INSTALL_DIR="${INSTALL_DIR:-/opt/geo-fail2ban}"
LEGACY_DIR="/opt/fail2ban-scripts"   # previous default; cleaned up on upgrade

# Firewall backend abstraction (auto-detects firewalld / ufw / iptables)
. scripts/firewall-lib.sh

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
}
print_success() { echo -e "${GREEN}✓ $1${NC}"; }
print_error()   { echo -e "${RED}✗ $1${NC}"; }
print_info()    { echo -e "${YELLOW}ℹ $1${NC}"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "This script must be run as root"
    echo "Please run: sudo bash install.sh"
    exit 1
fi

print_header "Geo-Fail2Ban Installation"
print_info "Install directory: $INSTALL_DIR"

# Step 1: Configuration (interactive — each question auto-skips after PROMPT_TIMEOUT seconds, default 60)
print_header "Configuration"
CONF=/etc/geo-fail2ban.conf
echo "Answer each prompt, or press Enter / wait ${PROMPT_TIMEOUT}s to skip (keeps the shown value)."
echo ""

# Defaults: an existing config, else a pre-filled config/.env, else blank.
if [ -f "$CONF" ]; then
    print_info "Existing $CONF found - its values are the defaults."
    # shellcheck disable=SC1090
    . "$CONF" 2>/dev/null || true
elif [ -f config/.env ]; then
    # shellcheck disable=SC1090
    . config/.env 2>/dev/null || true
fi

# ask <VAR> <prompt> [secret] — waits PROMPT_TIMEOUT seconds; keeps the current value on skip.
ask() {
    local __var="$1" __prompt="$2" __secret="${3:-}" __cur="${!1:-}" __ans="" __show="${!1:-}"
    [ "$__secret" = "secret" ] && [ -n "$__cur" ] && __show="********"
    if [ -n "$__cur" ]; then
        read -t "$PROMPT_TIMEOUT" -r -p "  ${__prompt} [${__show}]: " __ans || true
    else
        read -t "$PROMPT_TIMEOUT" -r -p "  ${__prompt} (Enter/${PROMPT_TIMEOUT}s to skip): " __ans || true
    fi
    echo
    [ -n "$__ans" ] && printf -v "$__var" '%s' "$__ans"
    return 0   # never let an empty answer (skip) trip 'set -e' in the caller
}

ask TELEGRAM_BOT_TOKEN "Telegram bot token"   secret
ask TELEGRAM_CHAT_ID   "Telegram chat ID"
ask IPINFO_API_TOKEN   "ipinfo.io API token"  secret
ask ABUSEIPDB_API_KEY  "AbuseIPDB API key"    secret

read -t "$PROMPT_TIMEOUT" -r -p "  Trusted whitelist IPs, space-separated (Enter/${PROMPT_TIMEOUT}s to skip): " WL_IPS || true
echo

# Geoblock downloads country zone files; ask unless --skip-geo was passed.
if [ "$SKIP_GEO" -eq 0 ]; then
    read -t "$PROMPT_TIMEOUT" -r -p "  Enable country geoblock (downloads zone files)? (Y/n, ${PROMPT_TIMEOUT}s): " _geo || true
    echo
    case "${_geo:-}" in [Nn]*) SKIP_GEO=1 ;; esac
fi

# Seed the config from an existing file or the template, then write the answers.
if [ ! -f "$CONF" ]; then
    if [ -f config/.env ]; then cp config/.env "$CONF"; else cp config/.env.example "$CONF"; fi
fi
set_conf() {  # set_conf KEY VALUE — idempotent; escapes sed metacharacters
    local k="$1" v
    v="$(printf '%s' "$2" | sed -e 's/[&|\\]/\\&/g')"
    if grep -qE "^${k}=" "$CONF"; then
        sed -i "s|^${k}=.*|${k}=\"${v}\"|" "$CONF"
    else
        printf '%s="%s"\n' "$k" "$2" >> "$CONF"
    fi
}
set_conf TELEGRAM_BOT_TOKEN "${TELEGRAM_BOT_TOKEN:-}"
set_conf TELEGRAM_CHAT_ID   "${TELEGRAM_CHAT_ID:-}"
set_conf IPINFO_API_TOKEN   "${IPINFO_API_TOKEN:-}"
set_conf ABUSEIPDB_API_KEY  "${ABUSEIPDB_API_KEY:-}"
chmod 600 "$CONF"
print_success "Configuration written to $CONF"

# Save whitelist IPs (one per line) for the firewall step / setup-firewall.sh
if [ -n "${WL_IPS:-}" ]; then
    { echo "# Geo-Fail2Ban whitelist (generated by install.sh)"
      for _ip in $WL_IPS; do echo "$_ip"; done; } > config/whitelist.txt
    print_success "Saved whitelist IPs to config/whitelist.txt"
fi

# Telegram credentials are required for the tool to do anything useful.
if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || printf '%s' "${TELEGRAM_BOT_TOKEN}" | grep -q 'YOUR_BOT_TOKEN_HERE'; then
    print_error "A Telegram bot token is required. Re-run and enter it, or edit $CONF."
    exit 1
fi
[ -z "${ABUSEIPDB_API_KEY:-}" ] && print_info "No AbuseIPDB key — reputation checks & blacklist import will be limited."
[ -z "${IPINFO_API_TOKEN:-}" ]  && print_info "No ipinfo.io token — GeoIP enrichment will be limited."

# Pre-flight: if a previous version is installed, uninstall it first.
# --keep-config preserves /etc/geo-fail2ban.conf (your credentials) so the
# fresh install reuses them. Done AFTER config validation above so we never
# tear down a working install only to bail out on a missing/placeholder config.
if [ -d "$INSTALL_DIR" ] || [ -d "$LEGACY_DIR" ] \
   || [ -f /etc/systemd/system/ipset-abuseipdb.service ] \
   || [ -f /etc/fail2ban/jail.d/abuseipdb.conf ] \
   || [ -f /etc/cron.d/fail2ban-abuseipdb ]; then
    print_info "Previous installation detected - uninstalling it first..."
    INSTALL_DIR="$INSTALL_DIR" bash scripts/uninstall.sh --yes --keep-config
    print_success "Previous version removed (kept /etc/geo-fail2ban.conf)"
fi

# Step 2: Install dependencies (fail2ban + ipset + iptables + curl + python requests).
# Cross-distro: pick whichever package manager this system has.
print_info "Installing dependencies..."
if command -v apt-get >/dev/null 2>&1; then
    apt-get update >/dev/null 2>&1
    DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban ipset iptables curl python3-requests >/dev/null 2>&1 \
        || DEBIAN_FRONTEND=noninteractive apt-get install -y fail2ban ipset iptables curl python3-pip >/dev/null 2>&1
elif command -v dnf >/dev/null 2>&1; then
    dnf install -y epel-release >/dev/null 2>&1 || true   # fail2ban lives in EPEL on RHEL
    dnf install -y fail2ban ipset iptables curl python3-requests >/dev/null 2>&1 \
        || dnf install -y fail2ban ipset iptables curl python3-pip >/dev/null 2>&1
elif command -v yum >/dev/null 2>&1; then
    yum install -y epel-release >/dev/null 2>&1 || true
    yum install -y fail2ban ipset iptables curl python3-requests >/dev/null 2>&1 \
        || yum install -y fail2ban ipset iptables curl python3-pip >/dev/null 2>&1
elif command -v zypper >/dev/null 2>&1; then
    zypper --non-interactive install fail2ban ipset iptables curl python3-requests >/dev/null 2>&1 || true
elif command -v pacman >/dev/null 2>&1; then
    pacman -Sy --noconfirm fail2ban ipset iptables curl python-requests >/dev/null 2>&1 || true
elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache fail2ban ipset iptables curl py3-requests >/dev/null 2>&1 || true
else
    print_error "No supported package manager found (apt/dnf/yum/zypper/pacman/apk)."
    echo "Install manually: fail2ban ipset iptables curl python3-requests"
    exit 1
fi
# Ensure the python 'requests' module is importable regardless of distro packaging
python3 -c 'import requests' 2>/dev/null \
    || pip3 install requests --break-system-packages >/dev/null 2>&1 \
    || pip3 install requests >/dev/null 2>&1 || true
print_success "Dependencies installed"

# Detect the firewall backend now that iptables/ufw/firewalld are present
FW_BACKEND="$(fw_detect)"
print_info "Firewall backend: $FW_BACKEND"
if [ "$FW_BACKEND" = "none" ]; then
    print_error "No usable firewall backend (need firewalld, ufw, or iptables+ipset)."
    exit 1
fi

# Step 3: Scripts
print_info "Installing scripts to $INSTALL_DIR ..."
mkdir -p "$INSTALL_DIR"
cp scripts/telegram_alert.py scripts/abuseipdb_blocker.py "$INSTALL_DIR/"
cp scripts/firewall-lib.sh "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR"/*.py "$INSTALL_DIR/firewall-lib.sh"
print_success "Scripts installed to $INSTALL_DIR"

# Step 4: Fail2ban configuration
print_info "Installing fail2ban configuration..."
[ -f /etc/fail2ban/jail.local ] && cp /etc/fail2ban/jail.local /etc/fail2ban/jail.local.bak
cp fail2ban/jail.local /etc/fail2ban/jail.local
cp fail2ban/jail.d/abuseipdb.conf /etc/fail2ban/jail.d/abuseipdb.conf
cp fail2ban/filter.d/abuseipdb.conf /etc/fail2ban/filter.d/abuseipdb.conf
cp fail2ban/action.d/telegram.conf /etc/fail2ban/action.d/telegram.conf
sed -i "s#/opt/geo-fail2ban#$INSTALL_DIR#g" /etc/fail2ban/action.d/telegram.conf
touch /var/log/abuseipdb.log
print_success "Fail2ban jails installed (sshd 24h + abuseipdb permanent)"

# Step 5: AbuseIPDB blacklist ipset (permanent, add-only)
print_info "Setting up AbuseIPDB blacklist ipset..."
ipset create abuseipdb-blacklist hash:ip family inet hashsize 16384 maxelem 500000 -exist
fw_block_set abuseipdb-blacklist
cp systemd/ipset-abuseipdb.service /etc/systemd/system/
# firewalld persists its own DROP rule, so the boot unit only restores the ipset.
# For ufw/iptables the unit re-adds the iptables rule at boot.
[ "$FW_BACKEND" = "firewalld" ] && sed -i '/--match-set abuseipdb-blacklist/d' /etc/systemd/system/ipset-abuseipdb.service
print_success "AbuseIPDB blacklist ipset + DROP rule active ($FW_BACKEND)"

# Step 6: Geoblock (optional)
if [ "$SKIP_GEO" -eq 0 ]; then
    print_info "Setting up country geoblock..."
    mkdir -p "$INSTALL_DIR/ipset-geo"
    cp ipset-geo/update.sh "$INSTALL_DIR/ipset-geo/update.sh"
    chmod +x "$INSTALL_DIR/ipset-geo/update.sh"
    cp systemd/ipset-geo.service /etc/systemd/system/
    cp cron/ipset-geo /etc/cron.d/ipset-geo
    sed -i "s#/opt/geo-fail2ban#$INSTALL_DIR#g" /etc/cron.d/ipset-geo
    print_info "Downloading country zone files (this can take a minute)..."
    "$INSTALL_DIR/ipset-geo/update.sh" || print_error "geoblock refresh failed (will retry via weekly cron)"
    fw_block_set geoblock
    [ "$FW_BACKEND" = "firewalld" ] && sed -i '/--match-set geoblock/d' /etc/systemd/system/ipset-geo.service
    print_success "Geoblock active (countries from GEOBLOCK_COUNTRIES in /etc/geo-fail2ban.conf)"
else
    print_info "Skipping geoblock (--skip-geo)"
fi

# Step 6b: Optionally apply the SSH/DNS whitelist now (only if IPs were given)
if [ -n "${WL_IPS:-}" ]; then
    print_warning "Restricting SSH/DNS to your whitelist will block all other sources."
    read -t "$PROMPT_TIMEOUT" -r -p "  Apply the SSH/DNS whitelist now via $FW_BACKEND? (y/N, ${PROMPT_TIMEOUT}s): " _apply || true
    echo
    case "${_apply:-}" in
        [Yy]*)
            fw_apply_whitelist $WL_IPS
            print_success "Whitelist applied (your current SSH IP was auto-included)."
            ;;
        *)  print_info "Skipped. Apply later with: sudo bash scripts/setup-firewall.sh" ;;
    esac
fi

# Step 7: Persistence + cron
print_info "Enabling boot persistence and cron jobs..."
systemctl daemon-reload
systemctl enable ipset-abuseipdb.service > /dev/null 2>&1
[ "$SKIP_GEO" -eq 0 ] && systemctl enable ipset-geo.service > /dev/null 2>&1
cp cron/fail2ban-abuseipdb /etc/cron.d/fail2ban-abuseipdb
sed -i "s#/opt/geo-fail2ban#$INSTALL_DIR#g" /etc/cron.d/fail2ban-abuseipdb
chmod 644 /etc/cron.d/*
print_success "Boot restore services enabled, daily blacklist cron installed"

# Step 8: First blacklist fetch (best effort - free API allows 5/day)
print_info "Fetching AbuseIPDB blacklist (may hit daily rate limit)..."
"$INSTALL_DIR/abuseipdb_blocker.py" 2>&1 | tail -2 || true
ipset save abuseipdb-blacklist > /etc/ipset-abuseipdb.conf

# Step 9: Restart fail2ban
print_info "Restarting Fail2Ban service..."
systemctl restart fail2ban
sleep 2
print_success "Fail2Ban restarted"

# Step 10: Verify installation
print_header "Verification"

FAIL=0
systemctl is-active --quiet fail2ban \
    && print_success "Fail2Ban service is running" \
    || { print_error "Fail2Ban service is not running"; FAIL=1; }
fail2ban-client status sshd > /dev/null 2>&1 \
    && print_success "sshd jail active (24h bans + Telegram alerts)" \
    || { print_error "sshd jail not active"; FAIL=1; }
fail2ban-client status abuseipdb > /dev/null 2>&1 \
    && print_success "abuseipdb jail active (PERMANENT bans, score >= threshold)" \
    || { print_error "abuseipdb jail not active"; FAIL=1; }
iptables -C INPUT -m set --match-set abuseipdb-blacklist src -j DROP 2>/dev/null \
    && print_success "Blacklist DROP rule present ($(ipset list -t abuseipdb-blacklist | awk '/Number of entries/{print $4}') IPs)" \
    || { print_error "Blacklist DROP rule missing"; FAIL=1; }
[ "$FAIL" -ne 0 ] && exit 1

# Step 11: Send a Telegram test alert so you can confirm it works end-to-end.
# Non-fatal: a delivery failure only warns (the rest of the install is fine).
print_info "Sending a test alert to Telegram..."
if "$INSTALL_DIR/telegram_alert.py" test >/dev/null 2>&1; then
    print_success "Test alert sent — check your Telegram chat"
else
    print_error "Could not send Telegram test alert — verify TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID in $CONF"
fi

print_header "Installation Complete! 🎉"

echo "How it works:"
echo "  • Failed SSH logins -> 24h ban + Telegram alert (BANNED/UNBANNED headers)"
echo "  • Banned IP with AbuseIPDB score >= threshold -> escalated to PERMANENT ban"
echo "  • AbuseIPDB blacklist imported daily into an add-only ipset (never expires)"
echo "  • Everything survives reboot (systemd restore units)"
echo ""
echo "Useful commands:"
echo "  sudo fail2ban-client status sshd"
echo "  sudo fail2ban-client status abuseipdb"
echo "  sudo ipset list -t abuseipdb-blacklist"
echo "  sudo bash tests/test_alert.sh"
echo ""
print_success "Geo-Fail2Ban is now protecting your server!"
echo ""
