# Fail2Ban Telegram Notification Action
# Author: Fail2Ban Team
# Documentation: man 5 fail2ban.actions

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart = /opt/geo-fail2ban/telegram_alert.py "start" "<name>" "0.0.0.0" "0"

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban.
# Values:  CMD
#
actionstop = /opt/geo-fail2ban/telegram_alert.py "stop" "<name>" "0.0.0.0" "0"

# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck =

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = /opt/geo-fail2ban/telegram_alert.py "Banned" "<name>" "<ip>" "<failures>"

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = /opt/geo-fail2ban/telegram_alert.py "Unbanned" "<name>" "<ip>" "<failures>"

[Init]
